### PR TITLE
Update simplified Chinese translation

### PR DESCRIPTION
**Pull request by 10935336**
The current version of the simplified Chinese translation has a lot of text missing.
Sorry I did see the poeditor translation, but I did not find how to start the translation.
I translated the key in en_us.json, please let me know if something is missing.

### CODE REVIEW

**Comment by JackFred2** [comment]
Apologies, I needed to approve you on poeditor but I didn't get a notification. My bad, you should be good to go now.
The translation here looks good, there are two keys missing: 
`"chesttracker.gui.reset_button_alt": "This can not be undone."`
`"key.chesttracker.searchforitem": "Search for Hovered Item"`
Otherwise, all good.
Otherwise

**Comment by 10935336** [comment]
OK，I have added the missing key.

**Review by JackFred2 — APPROVED** [review]

**Comment by JackFred2** [comment]
Thanks for the translation, I'll credit you as "a10935336" if that's OK?

**Comment by 10935336** [comment]
> Thanks for the translation, I'll credit you as "a10935336" if that's OK?

no problem

**Pull request merged**
