### PR TITLE
Create tr_tr.json

### PR DESCRIPTION
**Pull request by WinTone01**

### CODE REVIEW

**Comment by JackFred2** [comment]
Thank you for the translation! I'll merge in the morning; in the mean time are you happy to be credited as 'WinTone01' or would you want a different name listed?

**Comment by WinTone01** [comment]
> Thank you for the translation! I'll merge in the morning; in the mean time are you happy to be credited as 'WinTone01' or would you want a different name listed?

No, it's better for me to write WinTone01 :)

**Comment by JackFred2** [comment]
Just pushed a feature I was working on when this was opened - can you translate the [5 additional keys](https://github.com/JackFred2/ChestTracker/blob/1.20.4/src/client/resources/assets/chesttracker/lang/en_us.json#L106-L110)? Again thank you for the translations.

**Comment by WinTone01** [comment]
> Just pushed a feature I was working on when this was opened - can you translate the [5 additional keys](https://github.com/JackFred2/ChestTracker/blob/1.20.4/src/client/resources/assets/chesttracker/lang/en_us.json#L106-L110)? Again thank you for the translations.

I can do it in the morning

**Comment by WinTone01** [comment]
> Just pushed a feature I was working on when this was opened - can you translate the [5 additional keys](https://github.com/JackFred2/ChestTracker/blob/1.20.4/src/client/resources/assets/chesttracker/lang/en_us.json#L106-L110)? Again thank you for the translations.

Can you check again?

**Pull request merged**
