### PR TITLE
Hypixel Skyblock Support Improvements

### PR DESCRIPTION
**Pull request by VeritasDL**
re-did Backpack support,
added sack support (code is kinda cringe but meh)
added personal vault support

### CODE REVIEW

**Comment by VeritasDL** [comment]
pushed update to sack support :)

**Comment by JackFred2** [comment]
Looks good for the most part.

Re: sacks, seemed to be a bit flakey when I tried the CI build (mainly stuff like duplicated sacks); since they apparently merge like-sacks, and the titles don't have 'Large', I'll change it to using a unique position based on a hash of the title instead of the slot; I'll also change the sack counting to use oversize stacks so the screen / item list widget changes aren't needed

**Comment by VeritasDL** [comment]
yeah sacks are a bit bugged as im now learning from my own longer tests, mostly cuz im not the best at java but can smash rocks together, aha

**Comment by JackFred2** [comment]
No stress, PRs are a strong step for learning. Thanks for the PR!

**Comment by VeritasDL** [comment]
> No stress, PRs are a strong step for learning. Thanks for the PR!

thanks for the fixes Ill study and try to learn!
note for future fix
https://github.com/VeritasDL/ChestTracker/blob/1c63e912b6098e9845dbf4409a51852a8afc57d0/src/client/java/red/jackf/chesttracker/impl/compat/servers/hypixel/Skyblock.java#L107
`(stack.is(Items.GRAY_DYE))` 
this was added due to the Trophy Fishing Sack containing a gray dye item for unfound Trophy's 
[item tooltip ](https://veritasdl-sent-a.questionable.link/6Nbaeql_v.png)
item components dump
`{minecraft:lore=>LoreComponent[lines=[empty[style={!italic}], empty[style={!italic}, siblings=[literal{Undiscovered}[style={color=red}]]]], styledLines=[empty[style={color=dark_purple,!italic}], empty[style={color=dark_purple,!italic}, siblings=[literal{Undiscovered}[style={color=red}]]]]], minecraft:custom_name=>empty[style={!italic}, siblings=[literal{xxxxxxxxxxxx}[style={color=red,obfuscated}]]], minecraft:max_stack_size=>64, minecraft:enchantments=>ItemEnchantments{enchantments={}, showInTooltip=true}, minecraft:repair_cost=>0, minecraft:attribute_modifiers=>AttributeModifiersComponent[modifiers=[], showInTooltip=true], minecraft:rarity=>COMMON}` 
might be worth putting a check for either the "Undiscovered" tag or maybe the "obfuscated" tag as to not ignore all gray_dye

**Pull request merged**
